### ISSUE TITLE
Utworzyć schemat bazy danych

### ISSUE THREAD

**Issue by s0bieskii** [Event-Hub/EventsScraper#12]
TASKS
- znajdź stronkę do modelowania bazy (np: https://dbdiagram.io/d )
- daj swoje propozycje tabel
- DZIELIĆ SIĘ PROPOZYCJAMI NA WĄTKU!!!!

**Comment by s0bieskii** [comment]
Create a database scheam and models fields

**Comment by batonikleonardo** [comment]
Dodano katalog docs do projektu, w katalogu zamieszczono schemat bazy danych(obraz, plik źródłowy edytora draw.io)
PR : https://github.com/pdob-git/EventsScraper/pull/18

**Comment by poweredbychocolate** [comment]
Zamknięto poprzedni PR, dodano tabele dla scraper dashboard. Nowy PR https://github.com/pdob-git/EventsScraper/pull/30
