### ISSUE TITLE
Dodać do projektu liquibase, wraz z konfiguracją

### ISSUE THREAD

**Issue by batonikleonardo** [Event-Hub/EventsScraper#19]
1. Do projektu należy dodać zależności liquibase
2. Uzupełnić wymagane pliki konfiguracyjne(konfiguracja z wieloma plikami changeset)

* https://www.liquctiibase.org/get-started/best-practices

**Comment by poweredbychocolate** [comment]
Dodano zależności, konfigurację i changeset dla jednej tabeli z powodu wyrzucania błędy pustego katalogu w znaczniku includeAll
PR: https://github.com/pdob-git/EventsScraper/pull/27
